\mainmatter

# 零基础入手 R  {#usage}




## 介绍

本书使用 R 语言。R 是什么呢？在 R 的[官网](http://cran.r-project.org/)上是这么描述的：

> ... a freely available language and environment for statistical computing and graphics which provides a wide variety of statistical and graphical techniques: linear and nonlinear modelling, statistical tests, time series analysis, classification, clustering, etc. 

所以 R 是免费的、几乎适用于任何操作系统的一种语言和环境。在 R 里可安装上千个包，几乎可以做任何你想做的事情，具体来讲，它主要用于统计计算和统计图，包括线性和非线性模型、统计检验、时间序列分析、分类、聚类等。我们推荐通过 Rstudio 使用 R。

#### 安装 R 和 RStudio {-}

  1. [下载和安装 R。](http://cran.r-project.org/)
  2. [下载和安装 RStudio。](http://bit.ly/rstudiodownload)


#### R 工作目录 {-}


#### 安装 R 包 {-}
以 `ggplot2` 这个包为例，先运行 RStudio，在“包”选项，点击“安装包”，并且安装 `ggplot2` 包。（请勾选“安装依赖包”选项）。

就是这样！你现在应该准备好了。

#### 本书中的 R 示例 {-}

我们通过类似下面阴影框的形式对本书中大部分例子提供了 R 代码。


```r
f <- expression(x^2 - 5)
df <- deriv(f, 'x', func = TRUE)
```

注意：有时候我们也假设同一章节中较前的 R 代码已被执行；所以最好在每个章节都按顺序执行所提供的 R 代码。 

## R 基础

## R 中的数据结构

## 如何写 R 函数

## 如何在 R 中作图


## 有关 R 的学习资源

如果你从来没有用过 R，可以学习 DataCamp 的免费在线课程 [“R入门”](http://bit.ly/dcintro2r)。这个课程不会统计计算的内容，它只是教你R语言的基础。DataCamp 上还有 R 相关的[其他课程](https://www.datacamp.com/courses/tech:r)。 此外，[Coursera 上的 R 编程课程](https://www.coursera.org/learn/r-programming)也非常值得推荐。



